---

- name: Install Version Control
  yum: pkg={{ item }}
  with_items:
   - subversion
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Version Control Ubuntu
  apt: pkg={{ item }}
  with_items:
   - subversion
   - git
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy Git Config
  copy: src=files/gitconfig dest=/home/jared/.gitconfig
